spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: false
  application:
    name: URL Shortener
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 97f263ef4c87da
    password: 6a29040069aece
    properties:
      mail.smtp.auth: true

app:
  short-url-length: 5
  api-key-calls-limit: 8
  jwt-token-validity-seconds: 36000
  api-key-expiration-in-months: 1
  jwt-base64-secret: MzMzYjg3YTRmYmU0YmM4YzJkZWE4NTJlZGEzMDgzZjkzOWNjM2MwMWQ4NzI2MjgwZWU0MzM5ZTY0MGEzMjg1YzIwMjU1MWM5ZTNkMzg5YWNiMjExNGJlMTE4NjZlMWMxODIxNjYwMTBkZTRiZWRlNzU3MDc5ZThhMDcxMjlkMGE
  email-sender-address: no-reply@hrva.cc
  reset-token-expiration-in-hours: 1
  user-api-key-slots: 2
  inactive-visit-increment-per-ip-in-hours: 24
  ip-retention-duration-in-hours: 48
  deactivate-user-account-after-days: 365
  contact-email: info@localhost
  server-url: localhost
  max-login-attempts: 20
  frontend-url: http://localhost:8081
server:
  port: 8080