spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/dbchangelog.xml

management:
  endpoints:
    web:
      exposure:
        include: health, info

server:
  error:
    include-message: always

app:
  app-name: Open Url Shortener
  google-api:
    client-id: hrva.cc
    client-version: 1.0.0